/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Adder: typeof import('./components/Adder.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Deck: typeof import('./components/Deck.vue')['default']
    Decks: typeof import('./components/Decks.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./components/Searchbar.vue')['default']
    Stats: typeof import('./components/Stats.vue')['default']
    StatsComp: typeof import('./components/StatsComp.vue')['default']
    StatsComponent: typeof import('./components/StatsComponent.vue')['default']
    StatsCompt: typeof import('./components/StatsCompt.vue')['default']
  }
}
